# Site settings
title: 'Josh Keller'
email: joshmkeller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Deputy international editor at the The New York Times focusing on visual journalism. <a target='_blank' href='https://www.instagram.com/p/y4sYM6hiH2/'>Californian</a>. Find me on <a target='_blank' href='http://twitter.com/joshkellerjosh'>Twitter</a> or <a target='_blank' href='mailto:joshmkeller@gmail.com'>email</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joshkeller.github.io" # the base hostname & protocol for your site
twitter_username: joshkellerjosh
github_username:  joshkeller

# Build settings
markdown: kramdown
encoding: utf-8